name: Create Solana Token

on:
  repository_dispatch:
    types: [create_token]
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      token_name:
        description: 'Token Name'
        required: true
        type: string
      token_symbol:
        description: 'Token Symbol'
        required: true
        type: string
      token_decimals:
        description: 'Token Decimals'
        required: true
        type: string
        default: '9'
      token_supply:
        description: 'Token Supply'
        required: true
        type: string
      network:
        description: 'Network'
        required: true
        type: choice
        options:
        - devnet
        - mainnet
        default: 'devnet'
      revoke_freeze:
        description: 'Revoke Freeze Authority'
        required: false
        type: boolean
        default: false
      revoke_mint:
        description: 'Revoke Mint Authority'
        required: false
        type: boolean
        default: false

jobs:
  create-token:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract Token Parameters
      id: extract_params
      run: |
        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          echo "token_name=${{ github.event.client_payload.token_name }}" >> $GITHUB_OUTPUT
          echo "token_symbol=${{ github.event.client_payload.token_symbol }}" >> $GITHUB_OUTPUT
          echo "token_decimals=${{ github.event.client_payload.token_decimals }}" >> $GITHUB_OUTPUT
          echo "token_supply=${{ github.event.client_payload.token_supply }}" >> $GITHUB_OUTPUT
          echo "network=${{ github.event.client_payload.network }}" >> $GITHUB_OUTPUT
          echo "revoke_freeze=${{ github.event.client_payload.revoke_freeze }}" >> $GITHUB_OUTPUT
          echo "revoke_mint=${{ github.event.client_payload.revoke_mint }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "token_name=${{ github.event.inputs.token_name }}" >> $GITHUB_OUTPUT
          echo "token_symbol=${{ github.event.inputs.token_symbol }}" >> $GITHUB_OUTPUT
          echo "token_decimals=${{ github.event.inputs.token_decimals }}" >> $GITHUB_OUTPUT
          echo "token_supply=${{ github.event.inputs.token_supply }}" >> $GITHUB_OUTPUT
          echo "network=${{ github.event.inputs.network }}" >> $GITHUB_OUTPUT
          echo "revoke_freeze=${{ github.event.inputs.revoke_freeze }}" >> $GITHUB_OUTPUT
          echo "revoke_mint=${{ github.event.inputs.revoke_mint }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" = "issues" ]; then
          # Parse token parameters from issue body (JSON format expected)
          echo "token_name=Demo Token" >> $GITHUB_OUTPUT
          echo "token_symbol=DEMO" >> $GITHUB_OUTPUT
          echo "token_decimals=9" >> $GITHUB_OUTPUT
          echo "token_supply=1000000" >> $GITHUB_OUTPUT
          echo "network=devnet" >> $GITHUB_OUTPUT
          echo "revoke_freeze=false" >> $GITHUB_OUTPUT
          echo "revoke_mint=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana --version

    - name: Configure Solana CLI
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        if [ "${{ steps.extract_params.outputs.network }}" = "mainnet" ]; then
          solana config set --url https://api.mainnet-beta.solana.com
        else
          solana config set --url https://api.devnet.solana.com
        fi
        solana config get

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Rust programs
      run: |
        cd rust-programs
        cargo build --release

    - name: Create wallet keypair
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana-keygen new --no-bip39-passphrase --silent --outfile ./wallet.json
        echo "Wallet created: $(solana-keygen pubkey ./wallet.json)"

    - name: Request airdrop (devnet only)
      if: steps.extract_params.outputs.network == 'devnet'
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        WALLET_PUBKEY=$(solana-keygen pubkey ./wallet.json)
        echo "Requesting airdrop for wallet: $WALLET_PUBKEY"
        solana airdrop 2 $WALLET_PUBKEY --keypair ./wallet.json
        sleep 5
        solana balance $WALLET_PUBKEY

    - name: Create token with Python script
      id: create_token
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        python scripts/create_token.py \
          --wallet-path ./wallet.json \
          --name "${{ steps.extract_params.outputs.token_name }}" \
          --symbol "${{ steps.extract_params.outputs.token_symbol }}" \
          --description "Token created via GitHub Actions" \
          --supply ${{ steps.extract_params.outputs.token_supply }} \
          --decimals ${{ steps.extract_params.outputs.token_decimals }} \
          --image-url "" \
          --network ${{ steps.extract_params.outputs.network }} \
          ${{ steps.extract_params.outputs.revoke_mint == 'true' && '--revoke-mint-authority' || '' }} \
          ${{ steps.extract_params.outputs.revoke_freeze == 'true' && '--revoke-freeze-authority' || '' }}

    - name: Run Rust token operations
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        cd rust-programs
        cargo run --release -- \
          --wallet-path ../wallet.json \
          --mint-address "$(cat ../token_mint.txt)" \
          --operation verify

    - name: Generate token report
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        python scripts/generate_report.py \
          --mint-address "$(cat token_mint.txt)" \
          --network ${{ steps.extract_params.outputs.network }} \
          --wallet-address "$(solana-keygen pubkey ./wallet.json)"

    - name: Upload token creation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: token-creation-artifacts-${{ github.run_number }}
        path: |
          token_mint.txt
          token_metadata.json
          creation_log.txt
          token_report.html
          wallet.json
        retention-days: 30

    - name: Commit results to repository (optional)
      if: github.event.client_payload.commitResults == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Create results directory
        mkdir -p results/$(date +%Y-%m-%d)
        
        # Copy artifacts to results directory
        cp token_mint.txt results/$(date +%Y-%m-%d)/
        cp token_metadata.json results/$(date +%Y-%m-%d)/
        cp creation_log.txt results/$(date +%Y-%m-%d)/
        cp token_report.html results/$(date +%Y-%m-%d)/
        
        # Add and commit
        git add results/
        git commit -m "Add token creation results for $(date +%Y-%m-%d)"
        git push

    - name: Create workflow summary
      run: |
        echo "## 🪙 Token Creation Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Token Name:** ${{ github.event.client_payload.tokenName }}" >> $GITHUB_STEP_SUMMARY
        echo "**Token Symbol:** ${{ github.event.client_payload.tokenSymbol }}" >> $GITHUB_STEP_SUMMARY
        echo "**Network:** ${{ github.event.client_payload.network }}" >> $GITHUB_STEP_SUMMARY
        echo "**Initial Supply:** ${{ github.event.client_payload.initialSupply }}" >> $GITHUB_STEP_SUMMARY
        echo "**Decimals:** ${{ github.event.client_payload.decimals }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f token_mint.txt ]; then
          echo "**Token Mint Address:** \`$(cat token_mint.txt)\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event.client_payload.network }}" = "mainnet" ]; then
            echo "**Explorer Link:** https://explorer.solana.com/address/$(cat token_mint.txt)" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Explorer Link:** https://explorer.solana.com/address/$(cat token_mint.txt)?cluster=devnet" >> $GITHUB_STEP_SUMMARY
          fi
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Artifacts:** Available for download from this workflow run" >> $GITHUB_STEP_SUMMARY

    - name: Notify completion
      if: always()
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          echo "✅ Token creation completed successfully!"
        else
          echo "❌ Token creation failed. Check the logs for details."
        fi